// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/vmware/vsphere-automation-sdk-go/services/nsxt/infra/route_controllers (interfaces: BgpRouteTableClient)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	model "github.com/vmware/vsphere-automation-sdk-go/services/nsxt/model"
	gomock "go.uber.org/mock/gomock"
)

// MockBgpRouteTableClient is a mock of BgpRouteTableClient interface.
type MockBgpRouteTableClient struct {
	ctrl     *gomock.Controller
	recorder *MockBgpRouteTableClientMockRecorder
}

// MockBgpRouteTableClientMockRecorder is the mock recorder for MockBgpRouteTableClient.
type MockBgpRouteTableClientMockRecorder struct {
	mock *MockBgpRouteTableClient
}

// NewMockBgpRouteTableClient creates a new mock instance.
func NewMockBgpRouteTableClient(ctrl *gomock.Controller) *MockBgpRouteTableClient {
	mock := &MockBgpRouteTableClient{ctrl: ctrl}
	mock.recorder = &MockBgpRouteTableClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBgpRouteTableClient) EXPECT() *MockBgpRouteTableClientMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockBgpRouteTableClient) List(routeControllerIdParam, virtualNetworkAppliancePathParam string, networkPrefixParam *string) (model.BgpRIBListResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", routeControllerIdParam, virtualNetworkAppliancePathParam, networkPrefixParam)
	ret0, _ := ret[0].(model.BgpRIBListResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockBgpRouteTableClientMockRecorder) List(routeControllerIdParam, virtualNetworkAppliancePathParam, networkPrefixParam interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockBgpRouteTableClient)(nil).List), routeControllerIdParam, virtualNetworkAppliancePathParam, networkPrefixParam)
}
